/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": process.env.AWS_PROJECT_REGION,
  "aws_appsync_graphqlEndpoint": process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT,
  "aws_appsync_region": process.env.AWS_APPSYNC_REGION,
  "aws_appsync_authenticationType": process.env.AWS_APPSYNC_AUTHENTICATION_TYPE,

  /* if appsync authentication type api key */
  // "aws_appsync_authenticationType": process.env.AWS_APPSYNC_AUTHENTICATION_TYPE,
  // "aws_appsync_apiKey": "da2-o2ovcdhg45h4dacynafplhsdbe",

  /* if amplify authentication */
  "aws_cognito_region": process.env.COGNITO_REGION,
  "aws_user_pools_id": process.env.COGNITO_USER_POOL_ID,
  "aws_user_pools_web_client_id": process.env.COGNITO_CLIENT_ID,
};


export default awsmobile;
