export const DATETIME_FORMAT = {
  API_DATE: 'yyyy-MM-dd',
  API_FULL_DATE: 'YYYY-MM-DD',
  API_TIME: 'HH:mm:ss',
  API_DATETIME: 'YYYY-MM-DD HH:mm:ss',

  VIEW_HOUR: 'HH',
  VIEW_MINUTE: 'mm',
  VIEW_TIME: 'H:i',
  VIEW_DATE: 'Y/m/d',
  VIEW_FULL_DATE_TIME: 'Y/m/d H:i',
  VIEW_FULL_DATE: 'YYYY/MM/DD',
  VIEW_DATE_TIME_CUSTOM: 'YYYY/MM/DD HH:mm:ss',
  VIEW_DATE_TIME_MESSAGE: 'YYYY.MM.DD HH:mm',
  VIEW_HOUR_MINUTE: 'HH:mm',
  JP_LOCALIZE_DATE: 'YYYY年MM月DD日',
  VIEW_MONTH_YEAR: 'YYYY年MM月',
  MONTH_DATE_PICKER: 'YYYY/MM',
}
